name: Sedstart Cloud 

on:
  workflow_dispatch:

jobs:
  sedstart-run:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger SedStart test run
        uses: DasTapan09/no-code@main
        with:
          api_key: ${{ secrets.SEDSTART_API }}
          project_id: 2
          test_id: 3
          profile_id: 1
          browser: "chrome"
          headless: true
          environment: QA
