name: Sedstart Local macOS

on:
  workflow_dispatch:

jobs:
  sedstart-run:
    runs-on: macos-15

    steps:
      - name: Trigger SedStart test run
        uses: DasTapan09/gh-local@main
        with:
          api_key: ${{ secrets.SEDSTART_API }}
          project_id: 364
          suite_id: 316 
          profile_id: 616
          browser: "webkit"
          environment: QA
