name: Sedstart Local Linux

on:
  workflow_dispatch:

jobs:
  sedstart-run:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Xvfb (for headed runs)
        if: runner.os == 'Linux'
        uses: coactions/setup-xvfb@v1
        with:
          run: true
          options: "-screen 0 1920x1080x24"

      - name: Trigger SedStart test run
        uses: DasTapan09/runlocal@feature
        with:
          api_key: ${{ secrets.SEDSTART_API }}
          project_id: 
          test_id: 1629
          profile_id: 616
          environment: QA
