name: Run SedStart Test

on:
  workflow_dispatch:

jobs:
  sedstart-run:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger SedStart test run
        uses: DasTapan09/no-code
        with:
          apiKey: ${{ secrets.SEDSTART_API }}
          projectId: 270
          testId: 1186
          profileId: 330
          browser: chrome
          headless: false
          environment: Prod

